### ISSUE TITLE
error_pages may not be internal

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/ansible-nginx#101]
The default sites-available template makes the assumption that [custom error pages are internal locations](https://github.com/debops/ansible-nginx/blob/f13665eb3e31c99e3d2d2e51f3dc691fc607781c/templates/etc/nginx/sites-available/default.conf.j2#L658-L663). This may not be the case, I may want to forward the request to an upstream server or script.

For example:
```
item
  error_pages:
    '403 404': '= /index.php'
```
This would not work because the internal location block created by the template would prevent the request from being handled by the php location block. It would also cause any other requests that I might be trying to route though `index.php` to not work correctly.

I can work around this by using  `item.options` to define the custom error pages, but it would be nice if `item.error_pages` also worked.  I'd submit a patch but I'm not sure what would make the most sense.

**Comment by drybjed** [comment]
Do you think that per-server toggle that enables internal pages for all `error_pages` entries or disables them should be enough?

**Comment by MatthewMi11er** [comment]
I think that would work and would probably be easiest to implement.

The other option might be something like:

```
error_pages:
  - code: '403 404'
    location: '= /index.php'
    internal: false
```
And then conditionally exclude the location block per error code. That changes the syntax of the item config though.

**Comment by drybjed** [comment]
I have a different idea... Why not do something similar as with `item.location` and `item.location_list`?

`item.error_pages` stays the same with basic internal pages. `item.error_pages_list` uses a list of dictionaries which have more extensive configuration for each "error page".

**Comment by MatthewMi11er** [comment]
I like that. It would be much more flexible without being too messy.

**Comment by drybjed** [comment]
@MatthewMi11er Working on it at the moment, should be up soon.
