### ISSUE TITLE
Make nginx_version available via Ansible facts?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-nginx#121]
How should other roles check for the available Nginx version? I would propose Ansible facts. The other possibility would be to copy the version detection to the other role.

**Comment by drybjed** [comment]
Ansible facts should be the preferred, idempotent method. You can then use `ansible_local.nginx.version` variable to check the installed version, or fallback to some default. This makes checking the `nginx` package version in every role unnecessary.

The version of `nginx` package is checked by the role, that value could be saved in the facts if it's not already.

**Comment by ypid** [comment]
OK, I am converting the facts to a script and check the version there to always get the latest results without the need to rerun the role.
