### ISSUE TITLE
Log files in different directory

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-nginx#125]
The default template for the vhosts (/etc/nginx/sites-available/default.conf.j2) has the option to change the log file name of each vhost. It would be great to also be able to change the directory of the log files. This would help if someone only had sftp access to the machine and would like to see the logs.
### Example Sceme:
```
/srv/sftpusers
├── sftp_user
│   ├── files
│   └── sites
│       └── foo.bar
│           ├── logs
│           └── public
```

**Comment by drybjed** [comment]
Since I'm currently working on the `debops.nginx` role I'll look into it shortly.
