### ISSUE TITLE
Object has no attribute pki

### ISSUE THREAD

**Issue by Alan01252** [debops/ansible-nginx#14]
Hi guys,

The latest commit isn't working for me getting this error:

    TASK: [debops.nginx | Generate nginx server configuration] ******************** 
    fatal: [web01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'pki'", 'failed': True}
    fatal: [web01] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'pki'", 'failed': True}]}
    
    FATAL: all hosts have already failed -- aborting

I tried some obvious things but for the life of me I couldn't figure out which object is missing the .pki variable. Rolling back to the commit before the PKI stuff all worked.

Helped greatly appreciated :)

Cheers

Alan

**Comment by drybjed** [comment]
Hi, thanks for the heads up. This is almost definitely a missing check for ansible local fact existence, related to `debops.pki`. Looking into it.

**Comment by drybjed** [comment]
@Alan01252 This should do it. Also, a heads up - support for SSL certificates changed in nginx, this includes some variables. You might want to check your inventory and update it if necessary.

**Comment by Alan01252** [comment]
Wow rapid fix. Thanks drybjed!! Very much appreciated :)
