### ISSUE TITLE
Consider to disable `nginx_hsts_preload` by default

### ISSUE THREAD

**Issue by ypid** [debops/ansible-nginx#148]
Ref: https://github.com/debops/ansible-apache/pull/8/commits/15a1227bed15378f2c8260905ba7f8098f1cbd8d
This should probably be done when making the 0.2.0 release.

**Comment by drybjed** [comment]
Sounds good. :+1:

**Comment by ypid** [comment]
Disabled by default is also explicitly asked for by the preload list operators: https://hstspreload.org/#opt-in
