### ISSUE TITLE
Setting Referrer-Policy to no-referrer breaks applications

### ISSUE THREAD

**Issue by scibi** [debops/ansible-nginx#152]
Hi!

I'm wondering why default value of `Referrer-Policy` is set to `no-referrer`. Are there any particular reasons for that? Wouldn't it better to use `same-origin` policy?

Why I'm asking - Django uses Referrer header in it's CSRF protection middleware (https://docs.djangoproject.com/en/1.9/ref/csrf/#how-it-works). I know that I can change the policy in configuration but maybe default value is too strict?

**Comment by drybjed** [comment]
@ypid was the one who set it to `no-referrer` in https://github.com/debops/ansible-nginx/commit/124419f164ecd40751043944a2f2794ce2cfe874 commit. The `same-origin` sounds to me as a good default though, I'm in favor of changing it. Let me check the RFCs...

**Comment by drybjed** [comment]
From the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy page:

- **no-referrer**: The Referer header will be omitted entirely. No referrer information is sent along with requests

- **same-origin**: A referrer will be sent for same-site origins, but cross-origin requests will contain no referrer information.

**Comment by ypid** [comment]
Yes, after reevaluating and with the background that this breaks other things, `same-origin` sounds like the better default indeed.

I just tested it:

* `same-origin` https://webbkoll.dataskydd.net/en/results?url=https%3A%2F%2Fkeyhole.pubsrv.ypid.de%2F
* `no-referrer` https://webbkoll.dataskydd.net/en/results?url=https%3A%2F%2Fme.ypid.de%2F

As this header is still pretty new webbkoll.dataskydd.net proably does not check for `same-origin` yet (same as most browsers). I will stay with `no-referrer` for that reason but I am also in favor of this change in the role defaults.

**Comment by scibi** [comment]
I noticed this because now Chrome checks referrer policy :)
