### ISSUE TITLE
Redesign Content Security Policy support

### ISSUE THREAD

**Issue by ypid** [debops/ansible-nginx#155]
I think `csp_policy` is a bad name. `csp` already means Content Security Policy. So expanded this means "Content Security Policy policy". I plan to implement this differently in debops.apache: https://github.com/debops/ansible-apache/pull/19
This is also designed with a global `report-uri` in mind.

This can be changed when making the 0.2.0 release.
Related to: https://github.com/debops/ansible-nginx/issues/111
Related to: https://github.com/debops/ansible-nginx/pull/118
Ping: @carlalexander

**Comment by drybjed** [comment]
Sure, agreed. Perhaps the role could support the `csp_policy` for some time when new version is implemented, depending if there's not much overhead. This would allow easier conversion from one style to the other.

**Comment by ypid** [comment]
Thanks.

The issue is that `item.csp` still exists but would now have a different meaning. I am for a hard break this time.

**Comment by ypid** [comment]
Working on it.
