### ISSUE TITLE
"undefined variable" in task "Create default welcome page if enabled".

### ISSUE THREAD

**Issue by NickVolynkin** [debops/ansible-nginx#165]
I try to deploy DokuWiki by the [tutorial] and get the following error in the nginx playbook:

[tutorial]: https://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html#example-application-dokuwiki

```
TASK [debops.nginx : Create default welcome page if enabled] ***************************************************************************************************************************************************************************************************************
failed: [10.11.11.11] (item={u'welcome_domain': u'', u'name': [u'welcome'], u'csp_enabled': True, u'welcome': True, u'enabled': True, u'csp': u"default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'"}) => {"failed": true, "item": {"csp": "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'", "csp_enabled": true, "enabled": true, "name": ["welcome"], "welcome": true, "welcome_domain": ""}, "msg": "KeyError: 'undefined variable: 0'"}
ok: [10.11.11.11] => (item={u'name': [u'localhost', u'127.0.0.1', u'[::1]'], u'acme': False, u'welcome': True, u'enabled': True, u'ssl': False, u'welcome_css': False})
```

[Creation of default welcome page][default-page] seems unnecessary in this case, because I'm deploying a website. Maybe the error happens when calculating the condition – I'm not sure how to determine that.

[default-page]: https://github.com/debops/ansible-nginx/blob/master/tasks/nginx_servers.yml#L22

Please tell if I'm doing something wrong or how I could debug this error.

---
### Details

This happens on Debian 8 and Ubuntu 16.04, fresh deploys with just `debops bootstrap` and `debops` with no extra playbooks run on them. 
My controller machine is OS X with ansible 2.3.0.0, bash 4.4.12(1).

The only non-default variables are the following:
```
pki_internal: False
pki_authorities: []
```

Here is the 'unfolded' error message:
```python
{
    u'welcome_domain': u'',
    u'name': [u'welcome'],
    u'csp_enabled': True,
    u'welcome': True,
    u'enabled': True,
    u'csp': u"default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'"
}
```
```json
{
  "failed": true,
  "item": {
    "csp": "default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'",
    "csp_enabled": true,
    "enabled": true,
    "name": [
      "welcome"
    ],
    "welcome": true,
    "welcome_domain": ""
  },
  "msg": "KeyError: 'undefined variable: 0'"
}

```

**Comment by drybjed** [comment]
"Undefined variable: 0" is related to bugs in recent `python-jinja2` library. Try to update yours to version <2.8, it should fix the issue.

**Comment by NickVolynkin** [comment]
Thanks, it solved my problem.
