### ISSUE TITLE
IPv6 DNS-resolver causes nginx to fail

### ISSUE THREAD

**Issue by FloRinke** [debops/ansible-nginx#171]
nginx configuration fails, when there's an IPv6-Address present in /etc/resolv.conf:
```
nameserver fe80::1%ens192
nameserver 192.168.0.1
```
leads to `resolver 192.168.0.1 fe80::1%ens192 valid=300s;`
and this in turn causes nginx startup to fail:
```
Jul 15 16:52:03 hostname systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 15 16:52:03 hostname nginx[4206]: nginx: [emerg] invalid port in resolver "fe80::1%ens192" in /etc/nginx/sites-enabled/welcome.conf:37
Jul 15 16:52:03 hostname nginx[4206]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 15 16:52:03 hostname systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 15 16:52:03 hostname systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Jul 15 16:52:03 hostname systemd[1]: nginx.service: Unit entered failed state.
Jul 15 16:52:03 hostname systemd[1]: nginx.service: Failed with result 'exit-code'
```

In my case this happens on Debian Stretch, but I assume it will be the same for any other version of Debian/Ubuntu.

A simple fix would be to exclude v6-Addresses from being imported, but this is likely to cause trouble for an IPv6-only host. The better solution should be encapsulating IPv6s in brackets (like `resolver 192.168.0.1 [fe80::1%ens192] valid=300s;`), this should work according to nginx documentation.
I'll do some research and testing before sending you a PR.

**Comment by drybjed** [comment]
Thanks for the heads up. The `nginx` role template [already wraps IPv6 addresses in square brackets](https://github.com/debops/ansible-nginx/blob/master/templates/etc/nginx/sites-available/default.conf.j2#L546) using the `ipwrap` Ansible filter, but I guess the filter doesn't recognize IPv6 link-local addresses with zone indexes. I looked at the [`netaddr` documentation](https://netaddr.readthedocs.io/en/latest/tutorial_01.html) to see if the library handles them, but I don't see anything about zone indexes. Implementing that in the Ansible filter could be useful.

**Comment by FloRinke** [comment]
I was too focused on the awk-processing to notice the filters being applied there... You are right, the ipwrap filter relies on netaddr, and netaddr doesn't know/care about zone indexes.
I've submitted a new commit which should address your suggestion.
