### ISSUE TITLE
Basic auth configuration 

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-nginx#18]
Would be cool to have a config for auth_basic & auth_basic_user_file in nginx. 

Putting this two variables in the nginx template is easy, but where store the user_file with login and passwd?

**Comment by drybjed** [comment]
I have that on my mind, haven't gotten around to it yet. We should definitely have some way of generating these files via Ansible. I'm not sure if this should be tied into the `debops.nginx` role (primary, I think only "user"?) or make that a separate role... Probably the former though.

It should be a separate list of hashes, empty by default, with entries, and a separate variable with the filename. I think the proper place for `htpasswd` files should be in `/etc/nginx/auth_basic/` directory with `700` permissions. Inside there can be just one level for all the files initially, I don't see a need for subdirectories at this point.

With this we can have two modes of "operation", you can either generate passwords automatically, stored in `secret/` directory for idempotency, or provide an external file, which won't be overwritten when list of passwords is empty.

Also, any idea how to generate passwords without requiring `htpasswd` from `apache2-utils` package? I wonder if `lookup('password')` from Ansible could do it.
