### ISSUE TITLE
nginx listens on ipv6 only

### ISSUE THREAD

**Issue by triplem** [debops/ansible-nginx#32]
On debian wheezy (nginx 1.2) nginx was listening by default on ipv4 as well as ipv6. This is in later nginx versions turned off (see http://trac.nginx.org/nginx/ticket/345). 

An easy fix is to set the flag ipv6only to off. Otherwise the ipv4 address could be added explicitly as well.

**Comment by drybjed** [comment]
`debops.nginx` already handles that by adding `ipv6only=off` to default server. By default all servers are listening on `[::]:80` and/or `[::]:443`. If you use that in your server definition, you should be covered. If you don't specify any `item.listen` or `item.listen_ssl` directives in server config, `debops.nginx` template should use the correct ones automatically.

**Comment by triplem** [comment]
Guess me is doing something wrong here, but the ipv6only statement is not in the default server.

**Comment by drybjed** [comment]
Do you have current version of `debops.nginx`? Show the config you are using, especially `nginx_servers` list.

**Comment by triplem** [comment]
I just (re-)installed the latest version of debops.nginx. 

Looks like I had an old version installed ;-(

Can I make sure somehow to have always the latest version installed?

**Comment by drybjed** [comment]
`debops.nginx` is currently versioned, so you can compare the version you have installed with latest changes on GitHub. If you use `debops-update` command from the DebOps scripts, it can pull latest changes from all of the roles for you, you just need to run it from time to time.

To keep up with the changes in roles you can subscribe to them on GitHub by clicking on the "Watch" button in the repository page. Or, if you use a feed reader you could add the RSS feed from the repository to it. I've created an aggregator page for all the repositories on http://log.debops.org/ if you want to track all of them at once.

**Comment by triplem** [comment]
Unfortunately even though I do have the line 

```
listen [::]:443 ssl spdy default_server ipv6only=off;
```

in my default site config now, the site is still not available on external machines. So I get a response using 

```
curl --verbose --location --insecure 'https://localhost'
```

but I get none, if I try to connect to the same machine from my host.

Me is currently not using hte debops scripts but the ansible-galaxy command, I probably need to change this one though.

**Comment by drybjed** [comment]
You need to check a few places. Try `iptables -v -L` to see if `80` and `443` ports are open. Check `netstat -nlp` to see if nginx is listening on all interfaces.

**Comment by triplem** [comment]
Well, all of those are fine. As soon as I add "listen [::]:80 ipv6only=off;" to the default server (http), all is fine.

**Comment by drybjed** [comment]
Ah, I know what it is. `default_server` and `ipv6only=off` are options specified per port, so you need to have at least one nginx server with them for `80` and `443` ports. But they can only be present once in all nginx servers.

`debops.nginx` handles that using facts. If there's something wrong, remove the `/etc/ansible/facts.d/nginx.fact` file and re-run the role, it should regenerate the config files and select one as the default.

**Comment by triplem** [comment]
Ah, perfect. Just removed the fact, re-run ansible, now the dfault server is generated, even though without a name.

**Comment by drybjed** [comment]
That's fine, it will be used as a catch-all, and if you specify any servers with a name, they will take priority over the default.

**Comment by triplem** [comment]
sure, but the generated page could look more friendly ;-)

```
{# if item.name #}
{# item.name[0] #} is working!

{# else #}
Your website is working!

{# endif #}
```

That looks like the template in itself.

**Comment by drybjed** [comment]
It seems like an old file, you probably have old default `index.html` created by the role if the directory is empty. The new one doesn't do templates, just simple HTML. :-)

**Comment by triplem** [comment]
uh, okay. thanks.

most probably there needs to be a functinality to re-generate those old files if new ones are available, no?

**Comment by drybjed** [comment]
Not really. As for `index.html`, users could have their own which you don't want to overwrite if they exist.

**Comment by triplem** [comment]
Then all my questions are resolved. Thanks.
