### ISSUE TITLE
Order of locations is not preserved

### ISSUE THREAD

**Issue by scibi** [debops/ansible-nginx#53]
When you have multiple locations with regexp match the order is important. Right now locations are sorted alphabetically and it sometimes breaks configuration.

If you have:

    location:
      '~ b': |
        try_files $uri;
      '~ a': |
        try_files $uri;

The result will be:

    server {
        [...]
        location ~ a {
            try_files $uri;
        }

        location ~ b {
            try_files $uri;
        }
        [...]
    }

**Comment by scibi** [comment]
Never mind: item.location_list ;)

**Comment by drybjed** [comment]
Yes. `orderedDict` support in Ansible [is kind of considered](https://groups.google.com/forum/#!topic/ansible-devel/d1eUS46H-ZM) but it's not possible right now. `item.location_list` is your best bet.
