### ISSUE TITLE
Mailman/nginx dependency generates error in configuration file

### ISSUE THREAD

**Issue by stavnstrup** [debops/ansible-nginx#80]
Using the following variables in the mailman roles creates error in nginx configuraton file.

The culprit sees to be the string "*.", which I suspect should have been "*.example.org", however dumping the fact reveals that the ansible_domain is empty.

Logging in in the virtual machine and running "hostname -f" only gives the hostname "medusa2".

The mailmain/postfix component seems to work. Logging in and manually adding a member to a mailing list will produce a mail to the subscriber send with postfix.

Is there a standard way to assign the domain to the virtual machine?

Do you have a simple working Vagrant configuration and playbook, which demonstrates the debops.mailman role, and which could be part of the debops.mailman documentation?

I am currently not sure, if I need to configure variables in the roles mailman  dependens on.

Vars included in playbook (which uses the deboos.mailman role)

--- 
mailman_domains: ['medusa2.example.org'] 
mailman_site_admin: 'webmaster@example.org' 
mailman_lists: [{name: 'archcat', domain: 'example.org', owner: 'john@example.org', state: 'present', language: 'en', purge: 'false'}] 

Provisioning with ansible from Vagrant almost succeeds (1 task fails)

NOTIFIED: [debops.nginx | Test nginx and restart] *****************************  
failed: [default] => {"changed": true, "cmd": ["nginx", "-t"], "delta": "0:00:00.010620", "end": "2015-11-12 13:18:40.032475", "rc": 1, "start": "2015-11-12 13:18:40.021855", "warnings": []} 
stderr: nginx: [emerg] invalid hostname or wildcard "*." in /etc/nginx/sites-enabled/medusa2.example.org.conf:49 
nginx: configuration file /etc/nginx/nginx.conf test failed                                                                                                                                                                       

The generated medusa2.example.org.conf looks like this  (line 49 contains the string valid_"referers".

# Ansible managed: /etc/ansible/roles/debops.nginx/templates/etc/nginx/sites-available/default.conf.j2 modified on 2015-09-24 20:23:32 by root on ares 

# nginx server configuration for: 
#    - http://medusa2.example.org/ 
# generated by Ansible role: debops.mailman 

server { 
       listen [::]:80 default_server ipv6only=off; 

       server_name medusa2.example.org; 

       keepalive_timeout 60; 

       root /usr/lib/cgi-bin/mailman; 

       access_log /var/log/nginx/medusa2.example.org_access.log; 
       error_log /var/log/nginx/medusa2.example.org_error.log; 

       index index.html index.htm; 

       # Disallow access to hidden files and directories 
       location ~ /\. { 
               return 404; 
       } 

       location = /favicon.ico { 
               try_files /favicon.ico =204; 
               access_log off; 
               log_not_found off; 
       } 

       location = /nginx_status { 
               stub_status on; 
               access_log off; 
               allow 127.0.0.1/32; 
               allow ::1/128; 
               allow 10.0.2.15; 
               allow 192.168.33.10; 
               deny all; 
       } 

       include /etc/nginx/site-default.d/*.conf; 

       location /images/mailman { 
               alias /var/lib/mailman/icons; 
       } 

       location ~ ^/mailman/. { 
               valid_referers none blocked medusa2.example.org medusa2 *.; 
               if ($invalid_referer) { 
                       return 403; 
               } 
               gzip off; 
               root /usr/lib/cgi-bin/mailman; 
               fastcgi_split_path_info       ^/mailman(/[^/]*)(.*)$; 
               include       fastcgi_params; 
               fastcgi_param PATH_INFO       $fastcgi_path_info; 
               fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info; 
               fastcgi_pass  unix:/var/run/fcgiwrap-mailman.socket; 
       } 

       location /pipermail { 
               alias /var/lib/mailman/archives/public; 
               autoindex on; 
       } 

       location ~ ^/(mailman/?)?$ { 
               rewrite ^ /mailman/listinfo permanent; 
       } 

}

**Comment by drybjed** [comment]
If you don't have local DNS server which could indicate a domain, you can set a domain by adding something like:
```
127.0.1.1 hostname.example.org hostname
```
in `/etc/hosts` file. `debops.bootstrap` role can also do that for you, when you set `bootstrap_domain` variable in inventory.

I think that `debops.marilman` role is not fully working at the moment, I need to check that some time.

If you want to use DebOps with Vagrant, I suggest that you check out https://github.com/debops/examples repository. There are some single host and multi host Vagrant configuration examples there.

**Comment by stavnstrup** [comment]
That got rid of all errors during provisioning. But I am still unable to access any location mentioned in the configuration file except for

    http://medusa2.example.org/pipermail

Neither

    http://medusa2.example.org/mailman/listinfo

or 

    http://medusa2.example.org/nginx_status

nor anything else worked.

For the rest I get a 403. I am and old Apache guy - so I have to read up on the NGINX documentation.

What are the issues with the mailman role? One of the reasons, I discovered DebOps was because I was looking for mailman playbooks. Have configured mailman a couple of times and was looking forward to use an automated process.

I hope, I will be able to test everything on Vagrant otherwise I will have to test it in the cloud.

**Comment by drybjed** [comment]
When I last looked at Mailman role there were issues with installation, not sure now what exactly. I'll look into it shortly and try to fix any issues.

DebOps is not very well suited for Vagrant, for one a working domain and DNS setup is essential for most roles. I would skip Vagrant and try with a proper KVM setup in a subnetwork.

**Comment by stavnstrup** [comment]
Issue is not with the debobs.nginx role, but in the vars definition in the debops.mailman role.
