### ISSUE TITLE
ngx_http_spdy_module was superseded by ngx_http_v2_module

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/ansible-nginx#89]
As of [nginx 1.9.5](http://nginx.org/en/docs/http/ngx_http_v2_module.html) the `spdy` protocol has been replaced with `http2`.

Using the current templates Nginx gives a warning  about:
```
invalid parameter "spdy": ngx_http_spdy_module was superseded by ngx_http_v2_module
```

I think an additional check on line `798` of `templates/etc/nginx/sites-available/default.conf.j2` would fix it but I have not tested that yet.

**Comment by drybjed** [comment]
And `nginx` 1.9.6 is already in Stretch, so I guess soon somebody will push it to `jessie-backports`. Thanks for reporting this, a check in the template using `version_compare()` filter is the way to go.
