### ISSUE TITLE
Duplicate "root" directive error

### ISSUE THREAD

**Issue by tdavis** [debops/ansible-nginx#92]
Nginx fails to start because the following block is duplicated in generated ``sites-available`` files:

    root /srv/www/sites/<domain>/public;

    include snippets/acme-challenge.conf;

It appears at the very top of the ``server {}`` block and also after the ``server_name`` directives. It may relate to the recent refactoring of the ``print_root()`` macro, but I didn't look too closely.

**Comment by drybjed** [comment]
Thanks for the bug report. Do you have the `debops.pki` role enabled? Any custom configuration of the `nginx` role?

**Comment by tdavis** [comment]
I do have ``debops.pki`` enabled, I'm not doing much with the ``nginx`` role other than specifying servers (using the "default" template) and adding them to ``nginx_servers``.

**Comment by drybjed** [comment]
Hmm, I tried to reproduce this issue with current `master` code of `debops.nginx`, but can't.... Can you paste the generated configuration files? Maybe there would some clue as to what's causing this. Can you also post the role configuration you are using?

**Comment by tdavis** [comment]
Weird! I have attached a zip file (because github) with the configuration file and yaml used for the role. In this example I have tried to use ``root: False`` to disable it entirely, but now ``root False`` just appears in the file ;)

FWIW, everything works fine when I switch to 1ea127890 and run again.

[info.zip](https://github.com/debops/ansible-nginx/files/65676/info.zip)

**Comment by drybjed** [comment]
@tdavis Got the issue duplicated with your config, looking into it now. :-)

**Comment by drybjed** [comment]
@tdavis The issue should be fixed now.
