### ISSUE TITLE
Disabling status page doesn't work

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-nginx#94]
Not sure if I'm doing it right. I was trying to disable the status page block by setting `status: False` in the server configuration. That didn't seem to work. I looked at the code and the whole if condition doesn't make sense to me:

```
{% if item.status is defined and item.status or nginx_status or nginx_status_localhost %}
```

This is always going to be true. `nginx_status` and `nginx_status_localhost` are both global variables which shouldn't be false. On top of that, they're both arrays so I'm not even sure when they'd be false. 

I feel like if `status: False` is there. The if statement shouldn't run at all. Maybe you meant something like:

```
{% if item.status|d(True) and (nginx_status or nginx_status_localhost) %}
```

**Comment by drybjed** [comment]
i agree, `item.status` is a little jumbled up right now. I'll look at it in a bit, or you could try making a fix if you want.

**Comment by carlalexander** [comment]
Well does the condition make sense? I can make a PR with it.

**Comment by drybjed** [comment]
@carlalexander Yes, your version sounds fine - an `or` statement needs to use parsens to be correctly resolved by Python.
